version: "3.9"

# Deploy DB Only
services: 
  postgresql.service:
    container_name: ${POSTGRES_HOST}
    ports: 
    - ${POSTGRES_PORT}:5432
    image: ${POSTGRES_IMAGE}
    restart: ${GENERIC_RESTART}
    volumes:
      - ${VOLUME_POSTGRES}:/var/lib/postgresql/data
      - ./postgresql/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgresql/seed.backup:/tmp/seed.backup
      - ./postgresql/after_run:/tmp/after_run
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5432; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - shared_network

networks:
  shared_network:
    name: ${DEFAULT_NETWORK}