version: "3.9"

# Deploy pgtask only
services:
  postgres.task:
    image: ${PGTASK_IMAGE}
    container_name: ${PGTASK_NAME}
    restart: ${GENERIC_RESTART}
    volumes:
     - "./config/db.yaml:/opt/Tasks/db.yaml"
    networks:
      - shared_network

networks:
  shared_network:
    name: ${DEFAULT_NETWORK}